import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import chokidar from 'chokidar';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const UI_ROOT = path.resolve(__dirname, '..');
const COMPONENTS_DIR = path.join(UI_ROOT, 'src/components');
const INDEX_FILE = path.join(UI_ROOT, 'src/index.ts');
const STORIES_DIR = path.resolve(UI_ROOT, '../../apps/storybook/src/stories');

async function syncComponents() {
  if (!fs.existsSync(COMPONENTS_DIR)) return;

  const components = fs.readdirSync(COMPONENTS_DIR)
    .filter(file => file.endsWith('.tsx'));

  console.log(`🔍 Syncing ${components.length} components...`);

  // 1. Fix imports in components
  components.forEach(file => {
    const filePath = path.join(COMPONENTS_DIR, file);
    let content = fs.readFileSync(filePath, 'utf8');
    let changed = false;

    // Replace absolute lib/utils with relative
    if (content.includes('@org-design-system/components/lib/utils')) {
      content = content.replace(/@org-design-system\/components\/lib\/utils/g, '../lib/utils');
      changed = true;
    }

    // Replace absolute components with relative (if any)
    if (content.includes('@org-design-system/components/components/')) {
      content = content.replace(/@org-design-system\/components\/components\//g, './');
      changed = true;
    }

    if (changed) {
      fs.writeFileSync(filePath, content);
      console.log(`✅ Fixed imports in ${file}`);
    }

    // 2. Generate Storybook story if missing
    const name = file.replace('.tsx', '');
    const componentName = name.split('-').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join('');
    const storyPath = path.join(STORIES_DIR, `${componentName}.stories.tsx`);

    if (!fs.existsSync(storyPath)) {
      const storyContent = `import type { Meta, StoryObj } from '@storybook/react';
import { ${componentName} } from '@org-design-system/components';

const meta: Meta<typeof ${componentName}> = {
  title: '@org-design-system/components/${componentName}',
  component: ${componentName},
  parameters: {
    layout: 'centered',
  },
  tags: ['autodocs'],
};

export default meta;
type Story = StoryObj<typeof ${componentName}>;

export const Default: Story = {
  args: {},
};
`;
      fs.writeFileSync(storyPath, storyContent);
      console.log(`✨ Generated Storybook story for ${componentName}`);
    }
  });

  // 3. Update index.ts exports
  const exports = components.map(file => {
    const name = file.replace('.tsx', '');
    return `export * from './components/${name}';`;
  });

  const indexContent = `// This file is auto-generated by sync-components.ts
${exports.sort().join('\n')}
export * from './lib/utils';
`;

  fs.writeFileSync(INDEX_FILE, indexContent);
}

const isWatchMode = process.argv.includes('--watch') || process.argv.includes('-w');

if (isWatchMode) {
  console.log('🚀 Sync service started in watch mode...');
  syncComponents();

  const watcher = chokidar.watch(COMPONENTS_DIR, {
    ignoreInitial: true,
    persistent: true,
  });

  let timeout: NodeJS.Timeout;
  const debouncedSync = () => {
    clearTimeout(timeout);
    timeout = setTimeout(syncComponents, 100);
  };

  watcher.on('add', (filePath) => {
    console.log(`🆕 Component detected: ${path.basename(filePath)}`);
    debouncedSync();
  });

  watcher.on('change', (filePath) => {
    console.log(`📝 Component changed: ${path.basename(filePath)}`);
    debouncedSync();
  });

  watcher.on('unlink', (filePath) => {
    console.log(`🗑️ Component removed: ${path.basename(filePath)}`);
    debouncedSync();
  });

} else {
  syncComponents()
    .then(() => console.log('✨ Sync complete.'))
    .catch(console.error);
}
